---
is_permitted: false
lin_firewall: 'none'
## run test on internal port with random password
srv_pg_port: 55432
srv_pg_admin_password: "{{ lookup('password', '/tmp/testpass chars=ascii_letters') }}"
...
